<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Deque.AxeCore.Playwright" Version="4.12.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Microsoft.Playwright.Xunit" Version="1.61.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\samples\Bzs.Blazor.Demo\Bzs.Blazor.Demo.Catalog\Bzs.Blazor.Demo.Catalog.csproj" />
    <ProjectReference Include="..\..\samples\Bzs.Blazor.Demo\Bzs.Blazor.Demo\Bzs.Blazor.Demo.csproj"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\samples\Bzs.Blazor.Demo\Bzs.Blazor.Demo.WebAssembly\Bzs.Blazor.Demo.WebAssembly.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
